excerpt_separator: ""
markdown: kramdown
url: http://ctchurch.github.io
title: Working Title
email: chris.church@gmail.com
author: Chris Church
paginate: 5
google_analytics: 

theme: jekyll-theme-hacker
