excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ctchurch.github.io
title: A Million Micro-Outages
email: chris.church@gmail.com
author: Chris Church
description: DevOps, Pragmatic MicroServices, Open Source, and Sarcasm
paginate: 5
google_analytics: 
